# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidgetScenes = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetScenes.sizePolicy().hasHeightForWidth())
        self.tableWidgetScenes.setSizePolicy(sizePolicy)
        self.tableWidgetScenes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetScenes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetScenes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetScenes.setObjectName("tableWidgetScenes")
        self.tableWidgetScenes.setColumnCount(2)
        self.tableWidgetScenes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetScenes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetScenes.setHorizontalHeaderItem(1, item)
        self.tableWidgetScenes.horizontalHeader().setDefaultSectionSize(72)
        self.gridLayout_2.addWidget(self.tableWidgetScenes, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBoxPreview = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        self.groupBoxPreview.setObjectName("groupBoxPreview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPreview)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBoxPreview)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 591, 497))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_Preview = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_Preview.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Preview.setObjectName("gridLayout_Preview")
        self.labelPreview = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelPreview.setText("")
        self.labelPreview.setScaledContents(True)
        self.labelPreview.setObjectName("labelPreview")
        self.gridLayout_Preview.addWidget(self.labelPreview, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalSliderScale = QtWidgets.QSlider(self.groupBoxPreview)
        self.verticalSliderScale.setMinimum(10)
        self.verticalSliderScale.setMaximum(100)
        self.verticalSliderScale.setProperty("value", 100)
        self.verticalSliderScale.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderScale.setObjectName("verticalSliderScale")
        self.gridLayout_3.addWidget(self.verticalSliderScale, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBoxPreview, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuApplication = QtWidgets.QMenu(self.menubar)
        self.menuApplication.setObjectName("menuApplication")
        self.menuAutomator = QtWidgets.QMenu(self.menubar)
        self.menuAutomator.setObjectName("menuAutomator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelectDevice = QtWidgets.QAction(MainWindow)
        self.actionSelectDevice.setObjectName("actionSelectDevice")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionKill = QtWidgets.QAction(MainWindow)
        self.actionKill.setObjectName("actionKill")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.menuDevice.addAction(self.actionSelectDevice)
        self.menuApplication.addAction(self.actionRun)
        self.menuApplication.addAction(self.actionKill)
        self.menuApplication.addAction(self.actionRestart)
        self.menuAutomator.addAction(self.actionPlay)
        self.menuAutomator.addAction(self.actionPause)
        self.menuAutomator.addAction(self.actionStop)
        self.menuAutomator.addSeparator()
        self.menuAutomator.addAction(self.actionSettings)
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuAutomator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COCAutomator"))
        self.groupBox.setTitle(_translate("MainWindow", "Scenes"))
        item = self.tableWidgetScenes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.tableWidgetScenes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "accuracy"))
        self.groupBoxPreview.setTitle(_translate("MainWindow", "Preview"))
        self.verticalSliderScale.setToolTip(_translate("MainWindow", "Scale"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuApplication.setTitle(_translate("MainWindow", "Application"))
        self.menuAutomator.setTitle(_translate("MainWindow", "Automator"))
        self.actionSelectDevice.setText(_translate("MainWindow", "Select Device"))
        self.actionSelectDevice.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setShortcut(_translate("MainWindow", "Meta+R"))
        self.actionKill.setText(_translate("MainWindow", "Kill"))
        self.actionKill.setShortcut(_translate("MainWindow", "Ctrl+F2"))
        self.actionRestart.setText(_translate("MainWindow", "Restart"))
        self.actionRestart.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setShortcut(_translate("MainWindow", "F1"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setShortcut(_translate("MainWindow", "F2"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "F3"))
